export const UNKNOWN_OPTION = ["unknown", "Unknown / not assessed"];

export const FIELD_LABELS = {
  name: "Project name",
  state: "State",
  locality: "County / utility",
  capacityMW: "Capacity (MW)",
  phase: "Current phase",
  targetCOD: "Target COD",
  monthsToCOD: "Target COD",
  workloadType: "Workload",
  tenantStatus: "Tenant",
  landStatus: "Land control",
  permittingStatus: "Entitlements",
  taxIncentive: "Tax incentive",
  powerStatus: "Power",
  powerSource: "Power source",
  redundancy: "Redundancy",
  coolingType: "Cooling",
  waterSource: "Water source",
  contractType: "Contract type",
  gcStatus: "General contractor",
  longLeadStatus: "Long-lead equipment",
  financing: "Financing",
  insuranceStatus: "Insurance program",
  complianceStatus: "SOC 2 / ISO 27001",
  bcdrStatus: "BC/DR plan",
};

export const EMPTY_PROFILE = {
  name: "",
  state: "TX",
  locality: "",
  capacityMW: 100,
  phase: "site_selection",
  targetCOD: "",
  contractType: "unknown",
  gcStatus: "unknown",
  powerStatus: "unknown",
  powerSource: "unknown",
  longLeadStatus: "unknown",
  permittingStatus: "unknown",
  landStatus: "unknown",
  taxIncentive: "unknown",
  coolingType: "unknown",
  waterSource: "unknown",
  workloadType: "unknown",
  tenantStatus: "unknown",
  redundancy: "unknown",
  financing: "unknown",
  insuranceStatus: "unknown",
  complianceStatus: "unknown",
  bcdrStatus: "unknown",
};

export const PRESETS = [
  {
    label: "West Texas AI campus, early stage",
    profile: {
      ...EMPTY_PROFILE,
      name: "Permian Ridge Campus",
      state: "TX",
      locality: "Ector County, Oncor territory",
      capacityMW: 500,
      phase: "permitting",
      targetCOD: "2028-06-01",
      contractType: "cost_plus",
      gcStatus: "not_selected",
      powerStatus: "in_negotiation",
      powerSource: "hybrid",
      longLeadStatus: "not_ordered",
      permittingStatus: "in_progress",
      landStatus: "option",
      taxIncentive: "in_negotiation",
      coolingType: "liquid",
      waterSource: "groundwater",
      workloadType: "ai_training",
      tenantStatus: "loi",
      redundancy: "n_plus_1",
      financing: "project_finance",
      insuranceStatus: "not_started",
      complianceStatus: "not_started",
      bcdrStatus: "none",
    },
  },
  {
    label: "Northern Virginia hyperscale, under construction",
    profile: {
      ...EMPTY_PROFILE,
      name: "Loudoun Building 3",
      state: "VA",
      locality: "Loudoun County, Dominion territory",
      capacityMW: 96,
      phase: "construction",
      targetCOD: "2027-03-01",
      contractType: "gmp",
      gcStatus: "selected_dc_experienced",
      powerStatus: "utility_agreement",
      powerSource: "grid",
      longLeadStatus: "partially_ordered",
      permittingStatus: "complete",
      landStatus: "owned",
      taxIncentive: "executed",
      coolingType: "hybrid",
      waterSource: "municipal",
      workloadType: "inference",
      tenantStatus: "signed_hyperscale",
      redundancy: "2n",
      financing: "construction_loan",
      insuranceStatus: "placed",
      complianceStatus: "in_progress",
      bcdrStatus: "drafted",
    },
  },
  {
    label: "Ohio colocation, operating",
    profile: {
      ...EMPTY_PROFILE,
      name: "Columbus Colo Phase 1",
      state: "OH",
      locality: "Franklin County, AEP Ohio territory",
      capacityMW: 36,
      phase: "operations",
      targetCOD: "2025-09-01",
      contractType: "gmp",
      gcStatus: "selected_dc_experienced",
      powerStatus: "secured",
      powerSource: "grid",
      longLeadStatus: "ordered",
      permittingStatus: "complete",
      landStatus: "owned",
      taxIncentive: "executed",
      coolingType: "air",
      waterSource: "none",
      workloadType: "colo",
      tenantStatus: "signed_colo",
      redundancy: "n_plus_1",
      financing: "equity",
      insuranceStatus: "placed",
      complianceStatus: "certified",
      bcdrStatus: "tested",
    },
  },
  {
    label: "Arizona site under evaluation, partial information",
    profile: {
      ...EMPTY_PROFILE,
      name: "Maricopa Parcel B",
      state: "AZ",
      locality: "Maricopa County, APS territory",
      capacityMW: 200,
      phase: "site_selection",
      targetCOD: "",
      landStatus: "option",
      permittingStatus: "not_started",
      powerStatus: "in_negotiation",
      workloadType: "ai_training",
      tenantStatus: "speculative",
    },
  },
];

const withUnknown = (list) => [UNKNOWN_OPTION, ...list];

export const OPTIONS = {
  phase: [
    ["site_selection", "Site selection"],
    ["permitting", "Permitting"],
    ["procurement", "Procurement"],
    ["construction", "Construction"],
    ["commissioning", "Commissioning"],
    ["operations", "Operations"],
  ],
  contractType: withUnknown([
    ["gmp", "GMP"],
    ["lump_sum", "Lump sum"],
    ["cost_plus", "Cost plus"],
    ["design_build", "Design-build"],
  ]),
  gcStatus: withUnknown([
    ["not_selected", "Not selected"],
    ["selected_general", "Selected, general"],
    ["selected_dc_experienced", "Selected, DC experienced"],
  ]),
  powerStatus: withUnknown([
    ["unsecured", "Unsecured"],
    ["in_negotiation", "In negotiation"],
    ["utility_agreement", "Utility agreement"],
    ["secured", "Secured (ESA / PPA)"],
  ]),
  powerSource: withUnknown([
    ["grid", "Grid"],
    ["onsite_gas", "Onsite gas"],
    ["hybrid", "Hybrid"],
  ]),
  longLeadStatus: withUnknown([
    ["not_ordered", "Not ordered"],
    ["partially_ordered", "Partially ordered"],
    ["ordered", "Ordered"],
  ]),
  permittingStatus: withUnknown([
    ["not_started", "Not started"],
    ["in_progress", "In progress"],
    ["complete", "Complete"],
  ]),
  landStatus: withUnknown([
    ["not_secured", "Not secured"],
    ["option", "Option"],
    ["under_contract", "Under contract"],
    ["owned", "Owned"],
  ]),
  taxIncentive: withUnknown([
    ["none", "None"],
    ["in_negotiation", "In negotiation"],
    ["executed", "Executed"],
  ]),
  coolingType: withUnknown([
    ["air", "Air"],
    ["hybrid", "Hybrid"],
    ["liquid", "Liquid"],
  ]),
  waterSource: withUnknown([
    ["none", "None (closed loop)"],
    ["municipal", "Municipal"],
    ["groundwater", "Groundwater"],
    ["reclaimed", "Reclaimed"],
  ]),
  workloadType: withUnknown([
    ["ai_training", "AI training"],
    ["inference", "Inference"],
    ["hpc", "HPC"],
    ["colo", "Colocation"],
  ]),
  tenantStatus: withUnknown([
    ["speculative", "Speculative"],
    ["loi", "LOI"],
    ["signed_colo", "Signed, colo"],
    ["signed_hyperscale", "Signed, hyperscale"],
  ]),
  redundancy: withUnknown([
    ["n", "N"],
    ["n_plus_1", "N+1"],
    ["2n", "2N"],
  ]),
  financing: withUnknown([
    ["undecided", "Undecided"],
    ["equity", "Equity / balance sheet"],
    ["construction_loan", "Construction loan"],
    ["project_finance", "Project finance"],
  ]),
  insuranceStatus: withUnknown([
    ["not_started", "Not started"],
    ["in_progress", "In progress"],
    ["placed", "Placed"],
  ]),
  complianceStatus: withUnknown([
    ["not_started", "Not started"],
    ["in_progress", "In progress"],
    ["certified", "Certified"],
  ]),
  bcdrStatus: withUnknown([
    ["none", "None"],
    ["drafted", "Drafted"],
    ["tested", "Tested"],
  ]),
};